### PR TITLE
Define and implement a strawman stable JSON schema for output.

### LINKED ISSUE #368: Define and implement a stable JSON schema for output.
### Description

Experimental event streaming support was added in #286. Issues are reported as individual events with richly structured JSON that describe the failure. This is great for tools that need to work with and transform raw issues, but many tools will just want to use the human readable failure string, i.e: `Expectation failed: 1 == 2`. 

Swift-testing has done a lot of work to build up a nice message, and it would be nice to avoid reimplementing this in other tools (and keeping it up to date).

Feature: Add a new `message` field to the `issueRecorded` event that provides the human readable failure string. Bonus points if there is a markdown version of the string, as many tools can render markdown directly.

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to reproduce

_No response_

### swift-testing version/commit hash

_No response_

### Swift & OS version (output of `swift --version && uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by grynspan**
This PR defines a JSON schema for events output from swift-testing via either `--experimental-event-stream-output` or `abiEntryPoint_v0()`. The JSON schema needs to be formally reviewed separately.

We are already writing an experimental JSON stream using "snapshot" types and we don't want to break folks experimenting with it before we have a final JSON schema, so for now that remains the default. To opt into the new schema, pass `--experimental-event-stream-version 0` (note that this argument is not forwarded from `swift test`. See https://github.com/apple/swift-package-manager/pull/7534.)

Resolves #368.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test Linux

**Comment by grynspan** [comment]
@swift-ci please test

**Comment by grynspan** [comment]
@swift-ci please test

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift [hunk 1]
```diff
@@ -27,6 +27,11 @@ extension Event {
 
       /// The human-readable message.
       var stringValue: String
+
+      /// A concise version of ``stringValue``, if available.
+      ///
+      /// Not all messages include a concise string.
+      var conciseStringValue: String?
```
Comment (plemarquand) [inline Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:34]: How is this intended to be used?

**Review by plemarquand — APPROVED** [review]

File: Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift (hunk 1 above)
Comment (grynspan) [reply Sources/Testing/Events/Recorder/Event.HumanReadableOutputRecorder.swift:34]: This is a shorter version of the message's string. The longer version is output to `stderr` by default. The shorter version is what gets passed back in the JSON.

File: Sources/Testing/Events/Event.swift [hunk 2]
```diff
@@ -15,8 +15,11 @@ public struct Event: Sendable {
   public enum Kind: Sendable {
     /// A test run started.
     ///
+    /// - Parameters:
+    ///   - plan: The test plan of the run that started.
+    ///
     /// This event is the first event posted after ``Runner/run()`` is called.
-    case runStarted
+    indirect case runStarted(_ plan: Runner.Plan)
```
Comment (stmontgomery) [inline Sources/Testing/Events/Event.swift:22]: I suspect this is added because it's used elsewhere, but isn't this quite a large payload potentially? I wonder about the impact of that

But also (ironically): if we do add this here, for parity should we also be adding it to the corresponding _run ended_ event?

File: Sources/Testing/EntryPoints/ABIv0/ABIv0.swift [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+//
+// Copyright (c) 2024 Apple Inc. and the Swift project authors
+// Licensed under Apache License v2.0 with Runtime Library Exception
+//
+// See https://swift.org/LICENSE.txt for license information
+// See https://swift.org/CONTRIBUTORS.txt for Swift project authors
+//
+
+/// A namespace for ABI version 0 symbols.
+enum ABIv0: Sendable {}
```
Comment (stmontgomery) [inline Sources/Testing/EntryPoints/ABIv0/ABIv0.swift:12]: Not for right now, but if/when we expose this outside the module I'd like to bikeshed alternative naming conventions

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+    /// to the user.
+    var messages: [EncodedMessage]
+
+    /// The ID of the test associated with this event, if any.
+    var testID: EncodedTest.ID?
+
+    /// The ID of the test case associated with this event, if any.
+    ///
+    /// - Warning: Test cases are not yet part of the JSON schema.
+    var _testCase: EncodedTestCase?
```
Comment (stmontgomery) [inline Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:60]: I know this is non-final indicated by the underscore, and that's good. I think we ought to move in the direction of this being an ID of a test case, rather than encoding the full test case itself inline.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+            .pass
+          }
+        case .fail:
+            .fail
+        case .difference:
+            .difference
+        case .warning:
+            .warning
+        case .details:
+            .details
```
Comment (stmontgomery) [inline Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift:53]: nit: indentation in this init

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+
+    /// The symbol associated with this message.
+    var symbol: Symbol
+
+    /// The human-readable, unformatted text associated with this message.
+    var text: String
+
+    /// The human-readable, Markdown-formatted text associated with this
+    /// message, if any.
+    var markdown: String?
```
Comment (stmontgomery) [inline Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift:66]: is this speculative right now? Actually needed?

File: Sources/Testing/Events/Event.swift (hunk 2 above)
Comment (grynspan) [reply Sources/Testing/Events/Event.swift:22]: It's pretty chunky, yes, but remember that the value is CoW, so not as large as you might think. I'm open to alternative designs.

I left it out of the `runEnded` case precisely because it was relatively large.

File: Sources/Testing/EntryPoints/ABIv0/ABIv0.swift (hunk 3 above)
Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/ABIv0.swift:12]: This enum is definitely not ever meant to be _API_. It's a namespace for ABI-version-0 symbols only.

I'm open to alternatives.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift (hunk 4 above)
Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:60]: We don't encode the entire test case structure here, no.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift (hunk 5 above)
Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift:53]: Will fix.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift (hunk 6 above)
Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift:66]: Speculative at the request of @plemarquand.

Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedMessage.swift:66]: I'll remove it for now. We can add it later if we actually decide to implement it.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+
+    /// The source location of the event, if applicable.
+    var sourceLocation: SourceLocation?
+
+    /// The instant at which the event occurred on the current system's
+    /// suspending clock.
+    var timestamp: Double
+
+    /// The instant at which the event occurred on the wall clock.
+    var timestampSince1970: Double
```
Comment (stmontgomery) [inline Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:48]: These two timestamp properties feel like they could be grouped together into some kind of single type, maybe `EncodedInstant` ?

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+    /// Note that the set of encodable events is a subset of all events
+    /// generated at runtime by the testing library.
+    ///
+    /// For descriptions of individual cases, see ``Event/Kind``.
+    enum Kind: String, Sendable {
+      case runStarted
+      case testStarted
+      case testCaseStarted
+      case issueRecorded
+      case knownIssueRecorded
```
Comment (stmontgomery) [inline Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:30]: This `knownIssueRecorded` case is a little odd to me because the underlying types represent an `Issue` in general, which can either be non-known or known. And then separately, there is an Issue.Kind representing "_no known issue was recorded_", which is conceptually different. Is this representation confusing those?

Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:30]: This is a different abstraction than what we have in Swift, although we could approach it in other ways. I didn't build out a complete "issue" type in the schema because at the end of the day, handling an issue is a lot like handling any other event. `knownIssueRecorded` is distinct from `issueRecorded` because they're just kinds of event.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift (hunk 7 above)
Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:48]: Maybe. I originally just had `timestamp` as a single numeric value, but added the wall clock value later. @plemarquand What do you think?

Comment (plemarquand) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift:48]: I think wrapping them up in an `instant` field would make sense. 

If timestamp is a https://developer.apple.com/documentation/swift/suspendingclock maybe we could link to those docs to make it more clear when clock suspension might happen.

File: Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift (hunk 8 above)
Comment (grynspan) [reply Sources/Testing/EntryPoints/ABIv0/Encoded/ABIv0.EncodedEvent.swift]: Refactored.

**Review by dennisweissmann — APPROVED** [review]

File: Documentation/ABI/JSON.md [hunk 9]
```diff
@@ -0,0 +1,227 @@
...
+```
+<test> ::= {
+  "kind": <test-kind>,
+  "name": <string>, ; the unformatted function or non-qualified type name
+  ["displayName": <string>,] ; the user-supplied custom display name
+  "sourceLocation": <source-location>, ; where the test is defined
+  "id": <test-id>,
+}
+
+<test-kind> ::= "suite" | "function" | "parameterizedFunction"
```
Comment (stmontgomery) [inline Documentation/ABI/JSON.md:172]: I'm curious about rationale for parameterized tests being considered a distinct "kind"? Alternatively I could imagine them being represented as `test-kind ::= "function"`, with a distinct, optional Boolean property like `parameterized ::= true | false`

File: Documentation/ABI/JSON.md [hunk 10]
```diff
@@ -0,0 +1,227 @@
...
+```
+<bool> ::= true | false ; as in JSON
+
+<source-location> ::= {
+  "fileID": <string>, ; the Swift file ID of the file
+  "line": <number>,
+  "column": <number>,
+}
+
+<timestamp> ::= {
```
Comment (stmontgomery) [inline Documentation/ABI/JSON.md:51]: Is this `<timestamp>` used elsewhere in the spec?

File: Documentation/ABI/JSON.md [hunk 11]
```diff
@@ -0,0 +1,227 @@
...
+<event-record> ::= {
+  <version>,
+  "kind": "event",
+  "payload": <event>
+}
+```
+
+### Metadata
+
+Metadata records are reserved for future use.
```
Comment (stmontgomery) [inline Documentation/ABI/JSON.md:144]: This one feels quite speculative; if we need additional kinds of records, it seems like we can define them and extend this schema to describe them at that time, right? Rather than needing to explicitly reserve this now.

File: Documentation/ABI/JSON.md (hunk 10 above)
Comment (grynspan) [reply Documentation/ABI/JSON.md:51]: Should be `<instant>` now.

File: Documentation/ABI/JSON.md (hunk 11 above)
Comment (grynspan) [reply Documentation/ABI/JSON.md:144]: Will delete for now. I think we had the idea that we wanted to front-load some additional data, but we can amend this schema with that if/when we implement it.

File: Documentation/ABI/JSON.md (hunk 9 above)
Comment (grynspan) [reply Documentation/ABI/JSON.md:172]: No real rationale beyond "this is what I typed." If you feel strongly, I can refactor it.

Comment (grynspan) [reply Documentation/ABI/JSON.md]: Refactored.

**Review by stmontgomery — APPROVED** [review]

**Comment by grynspan** [comment]
@swift-ci please test
