### PR TITLE
Lazily evaluate test arguments only after determining their test will run, and support throwing expressions

### LINKED ISSUE #166: Support throwing errors from within `@Test` attributes
### Description

The argument parameter of `Test(_:_:arguments:)` is currently very limited.

Adding a version of `Test(_:_:arguments: () async throws -> C)` would greatly improve the parameterisation possibilities (e.g. async loading of parameters from a file).

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to reproduce

_No response_

### swift-testing version/commit hash

_No response_

### Swift & OS version (output of `swift --version && uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by stmontgomery**
This changes test declaration, discovery, planning, and running such that arguments to parameterized test functions are evaluated lazily, only after determining their test will run. It also adds support for throwing expressions in test arguments.

### Motivation:

When defining parameterized test functions, it can be useful to call throwing or asynchronous APIs — for example, to fetch the arguments from an external source. Today, the `@Test` macro supports `async` expressions but not `throws`. More problematic still: the arguments of _all_ tests get evaluated, even for tests which don't actually run (which may happen for various reasons). Evaluating the arguments of a test which won't run wastes time and resources, so we should try to avoid this, and support `throws` expressions too for better flexibility.

### Modifications:

- Modify the `@Test` macro and supporting library interfaces to surround test arguments in closures, so their evaluation can be lazy and deferred.
- Modify how test case arguments are stored on each `Test` instance accordingly.
- Modify the planning logic in `Runner.Plan` to defer evaluation of test cases until we determine whether each test will run.
- Update tests.

### Result:

Now, arguments to a parameterized test will only be evaluated if that test is actually going to run, and the expressions may include `try` and potentially throw an `Error`.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

Resolves #166
Resolves rdar://121531170

### CODE REVIEW

**Comment by stmontgomery** [comment]
@swift-ci please test

**Comment by stmontgomery** [comment]
@swift-ci please test

File: Sources/Testing/Test.swift [hunk 1]
```diff
@@ -154,7 +221,7 @@ public struct Test: Sendable {
     self.sourceLocation = sourceLocation
     self.containingTypeInfo = containingTypeInfo
     self.xcTestCompatibleSelector = xcTestCompatibleSelector
-    self._testCases = .init(rawValue: .init(testCases))
+    self.testCaseState = .unevaluated({ .init(try await testCases()) })
```
Comment (grynspan) [inline Sources/Testing/Test.swift:224]:
```suggestion
    self.testCaseState = .unevaluated { .init(try await testCases()) }
```

File: Sources/Testing/Test.swift [hunk 2]
```diff
@@ -183,7 +250,7 @@ extension Test {
       case name
       case displayName
       case sourceLocation
-      case testCases
+      case testCaseState
```
Comment (grynspan) [inline Sources/Testing/Test.swift:253]: I think in order to encode a test snapshot, we need to have the full set of test cases evaluated already, in which case this can just be `testCases` again.

Regardless, the keys in the snapshot encoding should generally mirror the public (or SPI) property names, not their backing storage.

File: Sources/TestingMacros/Support/AttributeDiscovery.swift [hunk 3]
```diff
@@ -133,6 +133,19 @@ struct AttributeInfo {
...
 
+    // Any arguments of the test declaration macro which specify test arguments
+    // need to be wrapped a closure so they may be evaluated lazily by the
+    // testing library at runtime. If any such arguments are present, they will
+    // begin with a labeled argument named `arguments:` and include all
+    // subsequent unlabeled arguments.
+    if let argumentsIndex = otherArguments.firstIndex(where: { $0.label?.tokenKind == .identifier("arguments") }) {
+      for index in argumentsIndex ..< otherArguments.endIndex {
+        var argument = otherArguments[index]
+        argument.expression = .init(ClosureExprSyntax { argument.expression })
```
Comment (grynspan) [inline Sources/TestingMacros/Support/AttributeDiscovery.swift:144]: This rewrites the arguments as detached nodes and will cause diagnostics we emit for them to fail to emit in the right location. Rewriting needs to be deferred to `functionArgumentList()`.

File: Tests/TestingTests/RunnerTests.swift [hunk 4]
```diff
@@ -36,6 +36,25 @@ private let randomNumber = Int.random(in: 0 ..< .max)
...
+  fatalError("Should never crash, since this should never be called by any test")
+}
+
+/// A test whose arguments always cause a `fatalError()` crash.
+///
+/// This test should always remain `.hidden` and never be selected to run. Its
+/// purpose is to validate that the arguments of tests which are not run are
+/// never evaluated.
+@Test(.hidden, arguments: fatalArguments())
+func parameterizedWithFatalArguments(i: Int) {}
```
Comment (grynspan) [inline Tests/TestingTests/RunnerTests.swift:56]: Seems like an opportunity to write an exit test here!

File: Sources/Testing/Support/Graph.swift [hunk 5]
```diff
@@ -676,6 +676,49 @@ extension Graph {
...
+  ///     The element representing that node is passed to this closure and its
+  ///     result is used as the corresponding value in the new graph.
+  ///
+  /// - Returns: A graph containing the transformed nodes of this graph at the
+  ///   same key paths.
+  ///
+  /// - Throws: Whatever is thrown by `transform`.
+  ///
+  /// This function iterates depth-first.
+  func mapValues<U>(_ transform: (Element) async throws -> U) async rethrows -> Graph<K, U> {
```
Comment (grynspan) [inline Sources/Testing/Support/Graph.swift:694]: It is intentional that we don't include the key path or key in the existing `mapValues()` definition (same as for `Dictionary`.) Can you elaborate why you need it here?

**Review by grynspan — CHANGES_REQUESTED** [review]
See comments above. I don't know why GitHub makes me type this. :)

File: Sources/Testing/Support/Graph.swift (hunk 5 above)
Comment (stmontgomery) [reply Sources/Testing/Support/Graph.swift:694]: I'm modifying all the mapValues APIs to accept key path in #372

File: Sources/TestingMacros/Support/AttributeDiscovery.swift (hunk 3 above)
Comment (stmontgomery) [reply Sources/TestingMacros/Support/AttributeDiscovery.swift]: Done!

**Comment by stmontgomery** [comment]
@swift-ci please test

File: Sources/TestingMacros/Support/AttributeDiscovery.swift [hunk 6]
```diff
@@ -193,6 +180,22 @@ struct AttributeInfo {
         ArrayElementSyntax(expression: traitExpr)
       }
     }))
+
+    var otherArguments = self.otherArguments
+
```
Comment (grynspan) [inline Sources/TestingMacros/Support/AttributeDiscovery.swift:185]: Stray blank line? Might be more concise to move the `var otherArguments` decl under the comment.

File: Sources/Testing/Test.swift [hunk 7]
```diff
@@ -68,24 +68,91 @@ public struct Test: Sendable {
...
+  ///
   /// For parameterized tests, each test case is associated with a single
   /// combination of parameterized inputs. For non-parameterized tests, a single
   /// test case is synthesized. For test suite types (as opposed to test
   /// functions), the value of this property is `nil`.
-  @_spi(ForToolsIntegrationOnly)
-  public var testCases: (some Sequence<Test.Case> & Sendable)? {
-    _testCases?.rawValue
+  var testCases: (some Sequence<Test.Case> & Sendable)? {
+    switch testCaseState {
```
Comment (grynspan) [inline Sources/Testing/Test.swift:111]:
```swift
guard case let .evaluated(result) = testCaseState else {
  preconditionFailure(...)
}
guard case let .success(testCases) = result else {
  preconditionFailure(...)
}
return testCases.rawValue
```

File: Sources/Testing/Test.swift [hunk 8]
```diff
@@ -207,12 +274,40 @@ extension Test {
     /// The source location of this test.
     public var sourceLocation: SourceLocation
 
+    /// An enumeration describing the evaluation state of a test's cases.
```
Comment (grynspan) [inline Sources/Testing/Test.swift:277]: Do we really need this in the snapshot?

File: Tests/TestingTests/MiscellaneousTests.swift [hunk 9]
```diff
@@ -405,41 +409,49 @@ struct MiscellaneousTests {
...
-    let parameterizedTestFunction2TestCases = try #require(parameterizedTestFunction2.testCases)
-    #expect(parameterizedTestFunction2TestCases.underestimatedCount == 100 * 100)
-    let parameterizedTestFunction2Parameters = try #require(parameterizedTestFunction2.parameters)
-    #expect(parameterizedTestFunction2Parameters.count == 2)
-    let parameterizedTestFunction2FirstParameter = try #require(parameterizedTestFunction2Parameters.first)
-    #expect(parameterizedTestFunction2FirstParameter.firstName == "i")
-    let parameterizedTestFunction2SecondParameter = try #require(parameterizedTestFunction2Parameters.last)
-    #expect(parameterizedTestFunction2SecondParameter.firstName == "j")
-    #expect(parameterizedTestFunction2SecondParameter.secondName == "value")
+    do {
```
Comment (grynspan) [inline Tests/TestingTests/MiscellaneousTests.swift:412]: Please double-check that we don't regress code coverage here. (I'm not saying we do, just being cautious.)

File: Tests/TestingTests/RunnerTests.swift (hunk 4 above)
Comment (grynspan) [reply Tests/TestingTests/RunnerTests.swift:56]: I wasn't kidding—why not write one?

File: Tests/TestingTests/Test.Case.Argument.IDTests.swift [hunk 10]
```diff
@@ -47,10 +49,11 @@ struct Test_Case_Argument_IDTests {
 
   @Test("One Identifiable parameter")
   func oneIdentifiableParameter() async throws {
-    let test = Test(
+    var test = Test(
       arguments: [MyIdentifiableArgument(id: "abc")],
       parameters: [Test.Parameter(index: 0, firstName: "value", type: MyIdentifiableArgument.self)]
     ) { _ in }
+    try await test.evaluateTestCases()
```
Comment (grynspan) [inline Tests/TestingTests/Test.Case.Argument.IDTests.swift:56]: Should we just have the fixture `Test.init` call this? It would make the overall change more concise.

**Review by grynspan — APPROVED** [review]

File: Sources/TestingMacros/Support/AttributeDiscovery.swift [hunk 11]
```diff
@@ -180,6 +180,22 @@ struct AttributeInfo {
...
+    // Any arguments of the test declaration macro which specify test arguments
+    // need to be wrapped a closure so they may be evaluated lazily by the
+    // testing library at runtime. If any such arguments are present, they will
+    // begin with a labeled argument named `arguments:` and include all
+    // subsequent unlabeled arguments.
+    if let argumentsIndex = otherArguments.firstIndex(where: { $0.label?.tokenKind == .identifier("arguments") }) {
+      for index in argumentsIndex ..< otherArguments.endIndex {
```
Comment (grynspan) [inline Sources/TestingMacros/Support/AttributeDiscovery.swift:192]: I think you could do:

```swift
arguments[argumentsIndex...] = arguments[argumentsIndex...].map { argument in
  ...
}
```

File: Sources/Testing/Test.swift (hunk 8 above)
Comment (stmontgomery) [reply Sources/Testing/Test.swift:277]: Meant to remove this - done!

File: Tests/TestingTests/Test.Case.Argument.IDTests.swift (hunk 10 above)
Comment (stmontgomery) [reply Tests/TestingTests/Test.Case.Argument.IDTests.swift:56]: I have re-organized things a bit so that we no longer need to call this on individual fixture test instances

**Comment by stmontgomery** [comment]
@swift-ci please test

File: Sources/Testing/Test.swift [hunk 12]
```diff
@@ -68,24 +68,91 @@ public struct Test: Sendable {
...
   /// For parameterized tests, each test case is associated with a single
   /// combination of parameterized inputs. For non-parameterized tests, a single
   /// test case is synthesized. For test suite types (as opposed to test
   /// functions), the value of this property is `nil`.
-  @_spi(ForToolsIntegrationOnly)
-  public var testCases: (some Sequence<Test.Case> & Sendable)? {
-    _testCases?.rawValue
+  var testCases: (some Sequence<Test.Case> & Sendable)? {
+    guard let testCasesState else {
+      return nil as AnySequence<Test.Case>?
```
Comment (grynspan) [inline Sources/Testing/Test.swift:112]: Is the `as` clause necessary here?

**Review by grynspan — APPROVED** [review]

File: Sources/Testing/Test.swift (hunk 12 above)
Comment (stmontgomery) [reply Sources/Testing/Test.swift:112]: Compiler can't infer the `some` result type without it, since this is the first `return` statement. (This technique was actually needed in the previous commit in this PR too, just in a different place)

File: Sources/TestingMacros/Support/AttributeDiscovery.swift (hunk 11 above)
Comment (stmontgomery) [reply Sources/TestingMacros/Support/AttributeDiscovery.swift:191]: Definitely open to this but I can't get this suggestion to compile, even if I drop `.lazy` or surround it with `Array(...)`

File: Sources/Testing/Test.swift (hunk 12 above)
Comment (grynspan) [reply Sources/Testing/Test.swift:112]: Boooo okay.

File: Sources/TestingMacros/Support/AttributeDiscovery.swift (hunk 11 above)
Comment (grynspan) [reply Sources/TestingMacros/Support/AttributeDiscovery.swift:191]: It's not critical, just a bit closer to our house style of _use all the monads!_. :) No worries.
