### PR TITLE
Lower Apple Platform requirement in Package.swift

### LINKED ISSUE #101: Lower the platform requirement
### Description

The current platform requirement makes it hard for other existing package to adopt swift-testing.
Consider lowering the requirement and mark related API with `@avaiable` mark.

### Expected behavior

A package with iOS 13 support can have a dependency on this package. 

### Actual behavior

A package with iOS 13 support can not have a dependency on this package. 

### Steps to reproduce

_No response_

### swift-testing version/commit hash

_No response_

### Swift & OS version (output of `swift --version && uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Lower Apple Platform requirement in Package.swift

### Motivation:

Close #101 

### Modifications:

Lower Apple Platform requirement in Package.swift

### Result:

A Package with iOS 13 support can at least have a dependency on it.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci please test

File: Package.swift [hunk 1]
```diff
@@ -17,10 +17,11 @@ let package = Package(
...
   platforms: [
-    .macOS(.v13),
-    .iOS(.v16),
-    .watchOS(.v9),
-    .tvOS(.v16),
+    .macOS(.v10_15),
+    .iOS(.v13),
+    .watchOS(.v6),
+    .tvOS(.v13),
+    .macCatalyst(.v13),
```
Comment (stmontgomery) [inline Package.swift:24]: @Kyle-Ye, would you like to update these versions to match those I proposed in my [reply](https://github.com/apple/swift-testing/issues/101#issuecomment-1808673624) to #101?

Comment (Kyle-Ye) [reply Package.swift:24]: Sorry, I still do not get the point. Could you elaborate on why we need macOS 13 instead of macOS 10.15 and watchOS 7 instead of watchOS 6? See https://github.com/apple/swift-testing/issues/101#issuecomment-1809525632.

Comment (Kyle-Ye) [reply Package.swift:24]: Specifically, I maintain a package which needs to support the above platform version. The current swift-testing configuration will block me from migrating to use swift-testing.

**Comment by stmontgomery** [comment]
Per my recent [reply](https://github.com/apple/swift-testing/issues/101#issuecomment-1814841731), I think we can proceed with this.

But first: I'm running CI again to confirm a theory that this will fail on macOS because I landed a change in #104 that requires newer OS versions after this PR was posted. I have a fix incoming for that, however, so we can land that first and then proceed with landing this.

**Comment by stmontgomery** [comment]
@swift-ci please test

**Review by stmontgomery — APPROVED** [review]
Approving, but waiting to merge until CI failures are resolved

**Comment by stmontgomery** [comment]
CI is failing in the way I would expect, now. Fixing that in #121

**Comment by stmontgomery** [comment]
@swift-ci please test
